name: smart_pantry
description: "Hybrid AI CulinaX – Pakistani cooking & pantry management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  flutter_tts: ^4.2.0
  timezone: ^0.10.0
  shared_preferences: ^2.3.3
  mobile_scanner: ^6.0.2
  image_picker: ^1.1.2
  google_mlkit_image_labeling: ^0.13.0
  google_generative_ai: ^0.4.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
